### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Angshuman1997** [MauryaRitesh/Facial-Expression-Detection#9]
I am getting this problem 

runfile('C:/Users/Angshuman Bardhan/.spyder-py3/temp.py', wdir='C:/Users/Angshuman Bardhan/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-4-e160254077f7>", line 1, in <module>
    runfile('C:/Users/Angshuman Bardhan/.spyder-py3/temp.py', wdir='C:/Users/Angshuman Bardhan/.spyder-py3')

  File "C:\Users\Angshuman Bardhan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Angshuman Bardhan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Angshuman Bardhan/.spyder-py3/temp.py", line 1, in <module>
    import cv2

  File "C:\Users\Angshuman Bardhan\Anaconda3\lib\site-packages\cv2\__init__.py", line 89, in <module>
    bootstrap()

  File "C:\Users\Angshuman Bardhan\Anaconda3\lib\site-packages\cv2\__init__.py", line 79, in bootstrap
    import cv2

ImportError: DLL load failed: The specified module could not be found.

**Comment by MauryaRitesh** [comment]
You need to install openCV. To do so, hit the following in your CMD:\
**pip install cv2**
